// This file is auto-generated by @hey-api/openapi-ts

export const Body_agent_install_skillSchema = {
    properties: {
        skill_zip: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'Skill Zip'
        }
    },
    type: 'object',
    required: ['skill_zip'],
    title: 'Body_agent-install_skill'
} as const;

export const Body_knowledge_base_upload_kb_documentSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_knowledge-base-upload_kb_document'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChatRequestSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ChatRequest',
    description: '发送消息请求'
} as const;

export const ChatResponseSchema = {
    properties: {
        reply: {
            type: 'string',
            title: 'Reply'
        },
        conversation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Conversation Id'
        }
    },
    type: 'object',
    required: ['reply', 'conversation_id'],
    title: 'ChatResponse',
    description: '聊天响应'
} as const;

export const ChunkOutSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'ChunkOut'
} as const;

export const ConversationCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            default: '新对话'
        }
    },
    type: 'object',
    title: 'ConversationCreate',
    description: '创建对话请求'
} as const;

export const ConversationResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'session_id'],
    title: 'ConversationResponse',
    description: '对话响应'
} as const;

export const DocumentOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        chunks_count: {
            type: 'integer',
            title: 'Chunks Count'
        },
        file_size: {
            type: 'integer',
            title: 'File Size'
        }
    },
    type: 'object',
    required: ['id', 'filename', 'status', 'chunks_count', 'file_size'],
    title: 'DocumentOut'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const KBCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'KBCreate'
} as const;

export const KBOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        document_count: {
            type: 'integer',
            title: 'Document Count'
        }
    },
    type: 'object',
    required: ['id', 'name', 'description', 'document_count'],
    title: 'KBOut'
} as const;

export const KBQueryRequestSchema = {
    properties: {
        query: {
            type: 'string',
            minLength: 1,
            title: 'Query',
            description: '检索问题，不能为空'
        },
        top_k: {
            type: 'integer',
            maximum: 20,
            minimum: 1,
            title: 'Top K',
            default: 4
        }
    },
    type: 'object',
    required: ['query'],
    title: 'KBQueryRequest'
} as const;

export const KBQueryResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/ChunkOut'
            },
            type: 'array',
            title: 'Results'
        },
        context: {
            type: 'string',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['results', 'context'],
    title: 'KBQueryResponse'
} as const;

export const MCPServerConnectResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        tools: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Tools'
        }
    },
    type: 'object',
    required: ['success', 'message'],
    title: 'MCPServerConnectResponse',
    description: `MCP Server 连接测试响应
当用户测试连接MCP Server时返回的结果`
} as const;

export const MCPServerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        transport_type: {
            type: 'string',
            enum: ['sse', 'stdio', 'streamable_http'],
            title: 'Transport Type'
        },
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        command: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        args: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Args'
        },
        env_vars: {
            additionalProperties: true,
            type: 'object',
            title: 'Env Vars'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'transport_type'],
    title: 'MCPServerCreate',
    description: `创建MCP Server请求
当用户想要添加一个新的MCP Server时, 发送这个请求。`
} as const;

export const MCPServerResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        transport_type: {
            type: 'string',
            title: 'Transport Type'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        command: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        args: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Args'
        },
        env_vars: {
            additionalProperties: true,
            type: 'object',
            title: 'Env Vars'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        tools: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Tools'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'transport_type', 'url', 'command', 'args', 'env_vars', 'is_active', 'tools'],
    title: 'MCPServerResponse',
    description: `MCP Server 响应
返回给用户的 MCP Server信息`
} as const;

export const MCPServerUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        command: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        args: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Args'
        },
        env_vars: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Env Vars'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'MCPServerUpdate',
    description: `更新MCP Server 请求
所有字段都是可选的，只更新用户提供的字段`
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProviderCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        provider_type: {
            type: 'string',
            title: 'Provider Type'
        },
        api_key: {
            type: 'string',
            title: 'Api Key'
        },
        model_name: {
            type: 'string',
            title: 'Model Name'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            default: false
        }
    },
    type: 'object',
    required: ['name', 'provider_type', 'api_key', 'model_name'],
    title: 'ProviderCreate',
    description: '创建请求体'
} as const;

export const ProviderOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        provider_type: {
            type: 'string',
            title: 'Provider Type'
        },
        model_name: {
            type: 'string',
            title: 'Model Name'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'name', 'provider_type', 'model_name', 'base_url', 'is_default', 'is_active'],
    title: 'ProviderOut',
    description: '响应体: 绝不返回明文 api_key'
} as const;

export const ProviderUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        is_default: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Default'
        }
    },
    type: 'object',
    title: 'ProviderUpdate',
    description: '更新请求体：所有字段可选'
} as const;

export const SystemPromptPublicSchema = {
    properties: {
        system_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'System Prompt'
        },
        is_custom: {
            type: 'boolean',
            title: 'Is Custom'
        },
        effective_prompt: {
            type: 'string',
            title: 'Effective Prompt'
        }
    },
    type: 'object',
    required: ['system_prompt', 'is_custom', 'effective_prompt'],
    title: 'SystemPromptPublic',
    description: '系统提示词状态（GET/PATCH 共用响应）'
} as const;

export const SystemPromptUpdateSchema = {
    properties: {
        system_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'System Prompt'
        }
    },
    type: 'object',
    title: 'SystemPromptUpdate',
    description: '更新系统提示词请求（传空串/null 即清空回落默认）'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        age: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Age'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        age: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Age'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        age: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Age'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;