// This file is auto-generated by @hey-api/openapi-ts

export const AgentRunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        input_text: {
            type: 'string',
            title: 'Input Text'
        },
        tool_calls_made: {
            type: 'integer',
            title: 'Tool Calls Made'
        },
        tokens_used: {
            type: 'integer',
            title: 'Tokens Used'
        },
        duration_ms: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Ms'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'status', 'input_text', 'tool_calls_made', 'tokens_used', 'duration_ms', 'error_message', 'created_at'],
    title: 'AgentRunPublic',
    description: '最近运行记录行'
} as const;

export const AttachmentOutSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        kind: {
            type: 'string',
            title: 'Kind'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        mime: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mime'
        },
        extracted_chars: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extracted Chars'
        },
        truncated: {
            type: 'boolean',
            title: 'Truncated',
            default: false
        }
    },
    type: 'object',
    required: ['id', 'kind', 'filename', 'size'],
    title: 'AttachmentOut',
    description: '上传成功后的附件元数据（前端据此渲染 chip / 缩略图）。'
} as const;

export const Body_agent_install_skillSchema = {
    properties: {
        skill_zip: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'Skill Zip'
        }
    },
    type: 'object',
    required: ['skill_zip'],
    title: 'Body_agent-install_skill'
} as const;

export const Body_agent_upload_attachmentSchema = {
    properties: {
        conversation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Conversation Id'
        },
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['conversation_id', 'file'],
    title: 'Body_agent-upload_attachment'
} as const;

export const Body_knowledge_base_upload_kb_documentSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_knowledge-base-upload_kb_document'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChatRequestSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ChatRequest',
    description: '发送消息请求'
} as const;

export const ChatResponseSchema = {
    properties: {
        reply: {
            type: 'string',
            title: 'Reply'
        },
        conversation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Conversation Id'
        }
    },
    type: 'object',
    required: ['reply', 'conversation_id'],
    title: 'ChatResponse',
    description: '聊天响应'
} as const;

export const ChunkOutSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'ChunkOut'
} as const;

export const ConversationCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            default: '新对话'
        },
        persona_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Persona Id'
        }
    },
    type: 'object',
    title: 'ConversationCreate',
    description: '创建对话请求'
} as const;

export const ConversationPersonaUpdateSchema = {
    properties: {
        persona_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Persona Id'
        }
    },
    type: 'object',
    title: 'ConversationPersonaUpdate',
    description: '会话绑定人设请求（null 表示解绑，回到用户默认提示词）'
} as const;

export const ConversationRenameSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ConversationRename',
    description: '重命名对话请求'
} as const;

export const ConversationResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        persona_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Persona Id'
        },
        is_enabled: {
            type: 'boolean',
            title: 'Is Enabled',
            default: true
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'session_id'],
    title: 'ConversationResponse',
    description: '对话响应'
} as const;

export const ConversationStatusUpdateSchema = {
    properties: {
        is_enabled: {
            type: 'boolean',
            title: 'Is Enabled'
        }
    },
    type: 'object',
    required: ['is_enabled'],
    title: 'ConversationStatusUpdate',
    description: '会话启用/停用请求（False 时新消息被管线拦截）'
} as const;

export const DeploymentSettingsPublicSchema = {
    properties: {
        open_registration: {
            type: 'boolean',
            title: 'Open Registration'
        },
        mode: {
            type: 'string',
            enum: ['single_user', 'multi_tenant'],
            title: 'Mode'
        },
        user_count: {
            type: 'integer',
            title: 'User Count'
        },
        env_open_registration: {
            type: 'boolean',
            title: 'Env Open Registration'
        }
    },
    type: 'object',
    required: ['open_registration', 'mode', 'user_count', 'env_open_registration'],
    title: 'DeploymentSettingsPublic',
    description: `部署设置状态（GET/PATCH 共用响应，仅超管可读）。

Attributes:
    open_registration: 当前生效值（本表有记录则取本表，否则回落 .env）。
    mode: **派生**的展示标签，由 open_registration 换算，不是独立配置项。
          True → "multi_tenant"（登录页开放注册）；False → "single_user"。
    user_count: 系统内账号数，供前端提示「切回单用户后已有账号仍可登录」。
    env_open_registration: \`.env\` 里的兜底值。便于管理员理解「本表没有
          记录时，系统在用什么」。超管专属端点，不对外泄露。`
} as const;

export const DeploymentSettingsUpdateSchema = {
    properties: {
        open_registration: {
            type: 'boolean',
            title: 'Open Registration'
        }
    },
    type: 'object',
    required: ['open_registration'],
    title: 'DeploymentSettingsUpdate',
    description: `更新部署设置请求。

目前只有**一个**运行时开关——匿名自助注册是否开放。其余与「模式」
相关的行为（超管建号、/admin 可见性、数据归属隔离）恒定不变，不随
开关走，因此这里也只有一个字段。`
} as const;

export const DocumentOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        chunks_count: {
            type: 'integer',
            title: 'Chunks Count'
        },
        file_size: {
            type: 'integer',
            title: 'File Size'
        }
    },
    type: 'object',
    required: ['id', 'filename', 'status', 'chunks_count', 'file_size'],
    title: 'DocumentOut'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const KBCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'KBCreate'
} as const;

export const KBOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        document_count: {
            type: 'integer',
            title: 'Document Count'
        }
    },
    type: 'object',
    required: ['id', 'name', 'description', 'document_count'],
    title: 'KBOut'
} as const;

export const KBQueryRequestSchema = {
    properties: {
        query: {
            type: 'string',
            minLength: 1,
            title: 'Query',
            description: '检索问题，不能为空'
        },
        top_k: {
            type: 'integer',
            maximum: 20,
            minimum: 1,
            title: 'Top K',
            default: 4
        }
    },
    type: 'object',
    required: ['query'],
    title: 'KBQueryRequest'
} as const;

export const KBQueryResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/ChunkOut'
            },
            type: 'array',
            title: 'Results'
        },
        context: {
            type: 'string',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['results', 'context'],
    title: 'KBQueryResponse'
} as const;

export const LogEntryOutSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        ts: {
            type: 'number',
            title: 'Ts'
        },
        level: {
            type: 'string',
            title: 'Level'
        },
        logger: {
            type: 'string',
            title: 'Logger'
        },
        source: {
            type: 'string',
            title: 'Source'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['id', 'ts', 'level', 'logger', 'source', 'message'],
    title: 'LogEntryOut'
} as const;

export const LogsOutSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/LogEntryOut'
            },
            type: 'array',
            title: 'Items'
        },
        latest_id: {
            type: 'integer',
            title: 'Latest Id'
        }
    },
    type: 'object',
    required: ['items', 'latest_id'],
    title: 'LogsOut'
} as const;

export const MCPServerConnectResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        tools: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Tools'
        }
    },
    type: 'object',
    required: ['success', 'message'],
    title: 'MCPServerConnectResponse',
    description: `MCP Server 连接测试响应
当用户测试连接MCP Server时返回的结果`
} as const;

export const MCPServerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        transport_type: {
            type: 'string',
            enum: ['sse', 'stdio', 'streamable_http'],
            title: 'Transport Type'
        },
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        command: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        args: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Args'
        },
        env_vars: {
            additionalProperties: true,
            type: 'object',
            title: 'Env Vars'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'transport_type'],
    title: 'MCPServerCreate',
    description: `创建MCP Server请求
当用户想要添加一个新的MCP Server时, 发送这个请求。`
} as const;

export const MCPServerResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        transport_type: {
            type: 'string',
            title: 'Transport Type'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        command: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        args: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Args'
        },
        env_vars: {
            additionalProperties: true,
            type: 'object',
            title: 'Env Vars'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        tools: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Tools'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'transport_type', 'url', 'command', 'args', 'env_vars', 'is_active', 'tools'],
    title: 'MCPServerResponse',
    description: `MCP Server 响应
返回给用户的 MCP Server信息`
} as const;

export const MCPServerUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        command: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        args: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Args'
        },
        env_vars: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Env Vars'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'MCPServerUpdate',
    description: `更新MCP Server 请求
所有字段都是可选的，只更新用户提供的字段`
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MessageOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        tool_calls: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tool Calls'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'role', 'content'],
    title: 'MessageOut',
    description: '会话消息响应（配置台消息列表用）'
} as const;

export const MessageTruncateRequestSchema = {
    properties: {
        message_id: {
            type: 'string',
            format: 'uuid',
            title: 'Message Id'
        },
        inclusive: {
            type: 'boolean',
            title: 'Inclusive',
            default: true
        }
    },
    type: 'object',
    required: ['message_id'],
    title: 'MessageTruncateRequest',
    description: '截断消息请求：删除指定消息及其后所有消息（inclusive=False 时保留该条）'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PersonaCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        prompt: {
            type: 'string',
            minLength: 1,
            title: 'Prompt'
        },
        avatar: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar'
        },
        default_provider_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Provider Id'
        },
        tools: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tools'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'prompt'],
    title: 'PersonaCreate',
    description: '创建人设请求'
} as const;

export const PersonaResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        prompt: {
            type: 'string',
            title: 'Prompt'
        },
        avatar: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar'
        },
        default_provider_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Provider Id'
        },
        tools: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tools'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'prompt', 'is_active'],
    title: 'PersonaResponse',
    description: '人设响应'
} as const;

export const PersonaUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        prompt: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prompt'
        },
        avatar: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar'
        },
        default_provider_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Provider Id'
        },
        tools: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tools'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'PersonaUpdate',
    description: '更新人设请求（只更新提供的字段）'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProviderBalanceOutSchema = {
    properties: {
        supported: {
            type: 'boolean',
            title: 'Supported'
        },
        provider: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider'
        },
        currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        remaining: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remaining'
        },
        total: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        used: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Used'
        },
        detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Detail'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['supported'],
    title: 'ProviderBalanceOut',
    description: '归一化后的余额查询结果（各服务商字段口径不同，统一到这里）。'
} as const;

export const ProviderCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        provider_type: {
            type: 'string',
            title: 'Provider Type'
        },
        capability: {
            type: 'string',
            enum: ['chat', 'stt', 'tts', 'embedding', 'rerank'],
            title: 'Capability',
            default: 'chat'
        },
        api_key: {
            type: 'string',
            title: 'Api Key'
        },
        model_name: {
            type: 'string',
            title: 'Model Name'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            default: false
        },
        supports_vision: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supports Vision'
        }
    },
    type: 'object',
    required: ['name', 'provider_type', 'api_key', 'model_name'],
    title: 'ProviderCreate',
    description: '创建请求体'
} as const;

export const ProviderKeyOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        key_mask: {
            type: 'string',
            title: 'Key Mask'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        fail_count: {
            type: 'integer',
            title: 'Fail Count'
        },
        cooldown_until: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooldown Until'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        }
    },
    type: 'object',
    required: ['id', 'key_mask', 'is_active', 'fail_count'],
    title: 'ProviderKeyOut',
    description: '密钥行：只回打码形态，绝不含明文/密文'
} as const;

export const ProviderKeysAddSchema = {
    properties: {
        keys: {
            items: {
                type: 'string'
            },
            type: 'array',
            minItems: 1,
            title: 'Keys'
        }
    },
    type: 'object',
    required: ['keys'],
    title: 'ProviderKeysAdd',
    description: '「添加更多」批量粘贴：一行一个 Key'
} as const;

export const ProviderKeysOutSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/ProviderKeyOut'
            },
            type: 'array',
            title: 'Items'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['items', 'count'],
    title: 'ProviderKeysOut'
} as const;

export const ProviderModelCreateSchema = {
    properties: {
        model_id: {
            type: 'string',
            maxLength: 200,
            minLength: 1,
            title: 'Model Id'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        }
    },
    type: 'object',
    required: ['model_id'],
    title: 'ProviderModelCreate',
    description: '「自定义模型」请求体'
} as const;

export const ProviderModelOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        model_id: {
            type: 'string',
            title: 'Model Id'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        }
    },
    type: 'object',
    required: ['id', 'model_id'],
    title: 'ProviderModelOut'
} as const;

export const ProviderModelsOutSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/ProviderModelOut'
            },
            type: 'array',
            title: 'Items'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['items', 'count'],
    title: 'ProviderModelsOut'
} as const;

export const ProviderOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        provider_type: {
            type: 'string',
            title: 'Provider Type'
        },
        capability: {
            type: 'string',
            title: 'Capability',
            default: 'chat'
        },
        model_name: {
            type: 'string',
            title: 'Model Name'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        supports_vision: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supports Vision'
        },
        timeout_seconds: {
            type: 'integer',
            title: 'Timeout Seconds',
            default: 120
        },
        proxy_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxy Url'
        },
        extra_headers: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Extra Headers',
            default: {}
        }
    },
    type: 'object',
    required: ['id', 'name', 'provider_type', 'model_name', 'base_url', 'is_default', 'is_active'],
    title: 'ProviderOut',
    description: '响应体: 绝不返回明文 api_key'
} as const;

export const ProviderUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        is_default: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Default'
        },
        supports_vision: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supports Vision'
        },
        timeout_seconds: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 600,
                    minimum: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timeout Seconds'
        },
        proxy_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxy Url'
        },
        extra_headers: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra Headers'
        }
    },
    type: 'object',
    title: 'ProviderUpdate',
    description: '更新请求体：所有字段可选'
} as const;

export const PublicSettingsSchema = {
    properties: {
        open_registration: {
            type: 'boolean',
            title: 'Open Registration'
        }
    },
    type: 'object',
    required: ['open_registration'],
    title: 'PublicSettings',
    description: `匿名可读的公开设置（仅用于登录页判断是否渲染「注册」入口）。

只暴露这一位布尔：它本身可由「试一次 POST /users/signup」的结果推得，
因此不构成额外泄露；而登录页必须在**鉴权之前**拿到它。`
} as const;

export const StatsDailyPointSchema = {
    properties: {
        date: {
            type: 'string',
            title: 'Date'
        },
        runs: {
            type: 'integer',
            title: 'Runs'
        },
        completed: {
            type: 'integer',
            title: 'Completed'
        },
        failed: {
            type: 'integer',
            title: 'Failed'
        },
        interrupted: {
            type: 'integer',
            title: 'Interrupted'
        },
        tokens: {
            type: 'integer',
            title: 'Tokens'
        },
        tool_calls: {
            type: 'integer',
            title: 'Tool Calls'
        },
        avg_duration_ms: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Duration Ms'
        }
    },
    type: 'object',
    required: ['date', 'runs', 'completed', 'failed', 'interrupted', 'tokens', 'tool_calls', 'avg_duration_ms'],
    title: 'StatsDailyPoint',
    description: '单日聚合点（UTC 日期）'
} as const;

export const StatsOverviewResponseSchema = {
    properties: {
        days: {
            type: 'integer',
            title: 'Days'
        },
        summary: {
            '$ref': '#/components/schemas/StatsSummary'
        },
        daily: {
            items: {
                '$ref': '#/components/schemas/StatsDailyPoint'
            },
            type: 'array',
            title: 'Daily'
        }
    },
    type: 'object',
    required: ['days', 'summary', 'daily'],
    title: 'StatsOverviewResponse',
    description: '统计概览：总计 + 按天序列'
} as const;

export const StatsSummarySchema = {
    properties: {
        runs: {
            type: 'integer',
            title: 'Runs'
        },
        completed: {
            type: 'integer',
            title: 'Completed'
        },
        failed: {
            type: 'integer',
            title: 'Failed'
        },
        interrupted: {
            type: 'integer',
            title: 'Interrupted'
        },
        tokens: {
            type: 'integer',
            title: 'Tokens'
        },
        tool_calls: {
            type: 'integer',
            title: 'Tool Calls'
        },
        avg_duration_ms: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Duration Ms'
        }
    },
    type: 'object',
    required: ['runs', 'completed', 'failed', 'interrupted', 'tokens', 'tool_calls', 'avg_duration_ms'],
    title: 'StatsSummary',
    description: '区间总计'
} as const;

export const SystemPromptPublicSchema = {
    properties: {
        system_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'System Prompt'
        },
        is_custom: {
            type: 'boolean',
            title: 'Is Custom'
        },
        effective_prompt: {
            type: 'string',
            title: 'Effective Prompt'
        }
    },
    type: 'object',
    required: ['system_prompt', 'is_custom', 'effective_prompt'],
    title: 'SystemPromptPublic',
    description: '系统提示词状态（GET/PATCH 共用响应）'
} as const;

export const SystemPromptUpdateSchema = {
    properties: {
        system_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'System Prompt'
        }
    },
    type: 'object',
    title: 'SystemPromptUpdate',
    description: '更新系统提示词请求（传空串/null 即清空回落默认）'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const ToolPermissionsPublicSchema = {
    properties: {
        shell_enabled: {
            type: 'boolean',
            title: 'Shell Enabled'
        },
        file_write_enabled: {
            type: 'boolean',
            title: 'File Write Enabled'
        },
        env_shell_enabled: {
            type: 'boolean',
            title: 'Env Shell Enabled'
        },
        env_file_write_enabled: {
            type: 'boolean',
            title: 'Env File Write Enabled'
        }
    },
    type: 'object',
    required: ['shell_enabled', 'file_write_enabled', 'env_shell_enabled', 'env_file_write_enabled'],
    title: 'ToolPermissionsPublic',
    description: `工具权限开关状态（GET/PATCH 共用响应）

Attributes:
    shell_enabled / file_write_enabled: 当前生效值（表 > .env）。
    env_shell_enabled / env_file_write_enabled: \`.env\` 兜底值，
        便于判断「网页开关没动时为什么是这个行为」。`
} as const;

export const ToolPermissionsUpdateSchema = {
    properties: {
        shell_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shell Enabled'
        },
        file_write_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Write Enabled'
        }
    },
    type: 'object',
    title: 'ToolPermissionsUpdate',
    description: '更新工具权限（只更新提供的字段）'
} as const;

export const TrashDocumentOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        kb_id: {
            type: 'string',
            format: 'uuid',
            title: 'Kb Id'
        },
        kb_name: {
            type: 'string',
            title: 'Kb Name'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        chunks_count: {
            type: 'integer',
            title: 'Chunks Count'
        },
        file_size: {
            type: 'integer',
            title: 'File Size'
        },
        deleted_at: {
            type: 'string',
            format: 'date-time',
            title: 'Deleted At'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['id', 'kb_id', 'kb_name', 'filename', 'status', 'chunks_count', 'file_size', 'deleted_at', 'expires_at'],
    title: 'TrashDocumentOut',
    description: `回收站条目：DocumentOut 的字段 + 归属库 + 生命周期时间点。

带 kb_name 是因为回收站是跨库的扁平列表，用户需要知道「这是哪个库的文件」。
expires_at 由后端算好下发，前端不必再复制一遍保留期规则。`
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        age: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Age'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        age: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Age'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        age: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Age'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;