// This file is auto-generated by @hey-api/openapi-ts

export type Body_agent_install_skill = {
    skill_zip: string;
};

export type Body_knowledge_base_upload_kb_document = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * 发送消息请求
 */
export type ChatRequest = {
    message: string;
};

/**
 * 聊天响应
 */
export type ChatResponse = {
    reply: string;
    conversation_id: string;
};

export type ChunkOut = {
    content: string;
    source?: (string | null);
};

/**
 * 创建对话请求
 */
export type ConversationCreate = {
    title?: string;
};

/**
 * 对话响应
 */
export type ConversationResponse = {
    id: string;
    title: string;
    session_id: string;
    created_at?: (string | null);
};

export type DocumentOut = {
    id: string;
    filename: string;
    status: string;
    chunks_count: number;
    file_size: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type KBCreate = {
    name: string;
    description?: (string | null);
};

export type KBOut = {
    id: string;
    name: string;
    description: (string | null);
    document_count: number;
};

export type KBQueryRequest = {
    /**
     * 检索问题，不能为空
     */
    query: string;
    top_k?: number;
};

export type KBQueryResponse = {
    results: Array<ChunkOut>;
    context: string;
};

/**
 * MCP Server 连接测试响应
 * 当用户测试连接MCP Server时返回的结果
 */
export type MCPServerConnectResponse = {
    success: boolean;
    message: string;
    tools?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * 创建MCP Server请求
 * 当用户想要添加一个新的MCP Server时, 发送这个请求。
 */
export type MCPServerCreate = {
    name: string;
    transport_type: 'sse' | 'stdio' | 'streamable_http';
    url?: (string | null);
    command?: (string | null);
    args?: Array<(string)>;
    env_vars?: {
        [key: string]: unknown;
    };
    is_active?: boolean;
};

export type transport_type = 'sse' | 'stdio' | 'streamable_http';

/**
 * MCP Server 响应
 * 返回给用户的 MCP Server信息
 */
export type MCPServerResponse = {
    id: string;
    name: string;
    transport_type: string;
    url: (string | null);
    command: (string | null);
    args: Array<(string)>;
    env_vars: {
        [key: string]: unknown;
    };
    is_active: boolean;
    tools: Array<{
        [key: string]: unknown;
    }>;
    created_at?: (string | null);
};

/**
 * 更新MCP Server 请求
 * 所有字段都是可选的，只更新用户提供的字段
 */
export type MCPServerUpdate = {
    name?: (string | null);
    url?: (string | null);
    command?: (string | null);
    args?: (Array<(string)> | null);
    env_vars?: ({
    [key: string]: unknown;
} | null);
    is_active?: (boolean | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * 创建请求体
 */
export type ProviderCreate = {
    name: string;
    provider_type: string;
    api_key: string;
    model_name: string;
    base_url?: (string | null);
    is_default?: boolean;
};

/**
 * 响应体: 绝不返回明文 api_key
 */
export type ProviderOut = {
    id: string;
    name: string;
    provider_type: string;
    model_name: string;
    base_url: (string | null);
    is_default: boolean;
    is_active: boolean;
};

/**
 * 更新请求体：所有字段可选
 */
export type ProviderUpdate = {
    name?: (string | null);
    api_key?: (string | null);
    model_name?: (string | null);
    base_url?: (string | null);
    is_default?: (boolean | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    age?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    age?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    age?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AgentCreateConversationData = {
    requestBody: ConversationCreate;
};

export type AgentCreateConversationResponse = (ConversationResponse);

export type AgentListConversationsData = {
    limit?: number;
    skip?: number;
};

export type AgentListConversationsResponse = (Array<ConversationResponse>);

export type AgentChatData = {
    conversationId: string;
    requestBody: ChatRequest;
};

export type AgentChatResponse = (ChatResponse);

export type AgentCreateMcpServerData = {
    requestBody: MCPServerCreate;
};

export type AgentCreateMcpServerResponse = (MCPServerResponse);

export type AgentListMcpServersData = {
    limit?: number;
    skip?: number;
};

export type AgentListMcpServersResponse = (Array<MCPServerResponse>);

export type AgentGetMcpServerData = {
    serverId: string;
};

export type AgentGetMcpServerResponse = (MCPServerResponse);

export type AgentUpdateMcpServerData = {
    requestBody: MCPServerUpdate;
    serverId: string;
};

export type AgentUpdateMcpServerResponse = (MCPServerResponse);

export type AgentDeleteMcpServerData = {
    serverId: string;
};

export type AgentDeleteMcpServerResponse = (unknown);

export type AgentConnectMcpServerData = {
    serverId: string;
};

export type AgentConnectMcpServerResponse = (MCPServerConnectResponse);

export type AgentListSkillsResponse = (Array<{
    [key: string]: unknown;
}>);

export type AgentGetSkillDetailData = {
    skillName: string;
};

export type AgentGetSkillDetailResponse = ({
    [key: string]: unknown;
});

export type AgentDeleteSkillData = {
    skillName: string;
};

export type AgentDeleteSkillResponse = ({
    [key: string]: unknown;
});

export type AgentScanSkillsResponse = ({
    [key: string]: unknown;
});

export type AgentInstallSkillData = {
    formData: Body_agent_install_skill;
};

export type AgentInstallSkillResponse = ({
    [key: string]: unknown;
});

export type KnowledgeBaseListKbsResponse = (Array<KBOut>);

export type KnowledgeBaseCreateKbData = {
    requestBody: KBCreate;
};

export type KnowledgeBaseCreateKbResponse = (KBOut);

export type KnowledgeBaseGetKbData = {
    kbId: string;
};

export type KnowledgeBaseGetKbResponse = (KBOut);

export type KnowledgeBaseDeleteKbData = {
    kbId: string;
};

export type KnowledgeBaseDeleteKbResponse = (unknown);

export type KnowledgeBaseUploadKbDocumentData = {
    formData: Body_knowledge_base_upload_kb_document;
    kbId: string;
};

export type KnowledgeBaseUploadKbDocumentResponse = (DocumentOut);

export type KnowledgeBaseListKbDocumentsData = {
    kbId: string;
};

export type KnowledgeBaseListKbDocumentsResponse = (Array<DocumentOut>);

export type KnowledgeBaseQueryKbData = {
    kbId: string;
    requestBody: KBQueryRequest;
};

export type KnowledgeBaseQueryKbResponse = (KBQueryResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProvidersListProvidersResponse = (Array<ProviderOut>);

export type ProvidersCreateProviderData = {
    requestBody: ProviderCreate;
};

export type ProvidersCreateProviderResponse = (ProviderOut);

export type ProvidersUpdateProviderData = {
    providerId: string;
    requestBody: ProviderUpdate;
};

export type ProvidersUpdateProviderResponse = (ProviderOut);

export type ProvidersDeleteProviderData = {
    providerId: string;
};

export type ProvidersDeleteProviderResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);