// This file is auto-generated by @hey-api/openapi-ts

export type Body_agent_install_skill = {
    skill_zip: string;
};

export type Body_knowledge_base_upload_kb_document = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * 发送消息请求
 */
export type ChatRequest = {
    message: string;
};

/**
 * 聊天响应
 */
export type ChatResponse = {
    reply: string;
    conversation_id: string;
};

export type ChunkOut = {
    content: string;
    source?: (string | null);
};

/**
 * 创建对话请求
 */
export type ConversationCreate = {
    title?: string;
};

/**
 * 重命名对话请求
 */
export type ConversationRename = {
    title: string;
};

/**
 * 对话响应
 */
export type ConversationResponse = {
    id: string;
    title: string;
    session_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

/**
 * 部署设置状态（GET/PATCH 共用响应，仅超管可读）。
 *
 * Attributes:
 * open_registration: 当前生效值（本表有记录则取本表，否则回落 .env）。
 * mode: **派生**的展示标签，由 open_registration 换算，不是独立配置项。
 * True → "multi_tenant"（登录页开放注册）；False → "single_user"。
 * user_count: 系统内账号数，供前端提示「切回单用户后已有账号仍可登录」。
 * env_open_registration: `.env` 里的兜底值。便于管理员理解「本表没有
 * 记录时，系统在用什么」。超管专属端点，不对外泄露。
 */
export type DeploymentSettingsPublic = {
    open_registration: boolean;
    mode: 'single_user' | 'multi_tenant';
    user_count: number;
    env_open_registration: boolean;
};

export type mode = 'single_user' | 'multi_tenant';

/**
 * 更新部署设置请求。
 *
 * 目前只有**一个**运行时开关——匿名自助注册是否开放。其余与「模式」
 * 相关的行为（超管建号、/admin 可见性、数据归属隔离）恒定不变，不随
 * 开关走，因此这里也只有一个字段。
 */
export type DeploymentSettingsUpdate = {
    open_registration: boolean;
};

export type DocumentOut = {
    id: string;
    filename: string;
    status: string;
    chunks_count: number;
    file_size: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type KBCreate = {
    name: string;
    description?: (string | null);
};

export type KBOut = {
    id: string;
    name: string;
    description: (string | null);
    document_count: number;
};

export type KBQueryRequest = {
    /**
     * 检索问题，不能为空
     */
    query: string;
    top_k?: number;
};

export type KBQueryResponse = {
    results: Array<ChunkOut>;
    context: string;
};

/**
 * MCP Server 连接测试响应
 * 当用户测试连接MCP Server时返回的结果
 */
export type MCPServerConnectResponse = {
    success: boolean;
    message: string;
    tools?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * 创建MCP Server请求
 * 当用户想要添加一个新的MCP Server时, 发送这个请求。
 */
export type MCPServerCreate = {
    name: string;
    transport_type: 'sse' | 'stdio' | 'streamable_http';
    url?: (string | null);
    command?: (string | null);
    args?: Array<(string)>;
    env_vars?: {
        [key: string]: unknown;
    };
    is_active?: boolean;
};

export type transport_type = 'sse' | 'stdio' | 'streamable_http';

/**
 * MCP Server 响应
 * 返回给用户的 MCP Server信息
 */
export type MCPServerResponse = {
    id: string;
    name: string;
    transport_type: string;
    url: (string | null);
    command: (string | null);
    args: Array<(string)>;
    env_vars: {
        [key: string]: unknown;
    };
    is_active: boolean;
    tools: Array<{
        [key: string]: unknown;
    }>;
    created_at?: (string | null);
};

/**
 * 更新MCP Server 请求
 * 所有字段都是可选的，只更新用户提供的字段
 */
export type MCPServerUpdate = {
    name?: (string | null);
    url?: (string | null);
    command?: (string | null);
    args?: (Array<(string)> | null);
    env_vars?: ({
    [key: string]: unknown;
} | null);
    is_active?: (boolean | null);
};

export type Message = {
    message: string;
};

/**
 * 会话消息响应（配置台消息列表用）
 */
export type MessageOut = {
    id: string;
    role: string;
    content: string;
    tool_calls?: (Array<{
    [key: string]: unknown;
}> | null);
    created_at?: (string | null);
};

/**
 * 截断消息请求：删除指定消息及其后所有消息（inclusive=False 时保留该条）
 */
export type MessageTruncateRequest = {
    message_id: string;
    inclusive?: boolean;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * 创建请求体
 */
export type ProviderCreate = {
    name: string;
    provider_type: string;
    api_key: string;
    model_name: string;
    base_url?: (string | null);
    is_default?: boolean;
};

/**
 * 响应体: 绝不返回明文 api_key
 */
export type ProviderOut = {
    id: string;
    name: string;
    provider_type: string;
    model_name: string;
    base_url: (string | null);
    is_default: boolean;
    is_active: boolean;
};

/**
 * 更新请求体：所有字段可选
 */
export type ProviderUpdate = {
    name?: (string | null);
    api_key?: (string | null);
    model_name?: (string | null);
    base_url?: (string | null);
    is_default?: (boolean | null);
};

/**
 * 匿名可读的公开设置（仅用于登录页判断是否渲染「注册」入口）。
 *
 * 只暴露这一位布尔：它本身可由「试一次 POST /users/signup」的结果推得，
 * 因此不构成额外泄露；而登录页必须在**鉴权之前**拿到它。
 */
export type PublicSettings = {
    open_registration: boolean;
};

/**
 * 系统提示词状态（GET/PATCH 共用响应）
 */
export type SystemPromptPublic = {
    system_prompt: (string | null);
    is_custom: boolean;
    effective_prompt: string;
};

/**
 * 更新系统提示词请求（传空串/null 即清空回落默认）
 */
export type SystemPromptUpdate = {
    system_prompt?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * 回收站条目：DocumentOut 的字段 + 归属库 + 生命周期时间点。
 *
 * 带 kb_name 是因为回收站是跨库的扁平列表，用户需要知道「这是哪个库的文件」。
 * expires_at 由后端算好下发，前端不必再复制一遍保留期规则。
 */
export type TrashDocumentOut = {
    id: string;
    kb_id: string;
    kb_name: string;
    filename: string;
    status: string;
    chunks_count: number;
    file_size: number;
    deleted_at: string;
    expires_at: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    age?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    age?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    age?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AgentCreateConversationData = {
    requestBody: ConversationCreate;
};

export type AgentCreateConversationResponse = (ConversationResponse);

export type AgentListConversationsData = {
    limit?: number;
    skip?: number;
};

export type AgentListConversationsResponse = (Array<ConversationResponse>);

export type AgentRenameConversationData = {
    conversationId: string;
    requestBody: ConversationRename;
};

export type AgentRenameConversationResponse = (ConversationResponse);

export type AgentDeleteConversationData = {
    conversationId: string;
};

export type AgentDeleteConversationResponse = (unknown);

export type AgentExportConversationData = {
    conversationId: string;
    /**
     * 导出格式：md / txt / json / docx / pdf
     */
    format?: 'md' | 'txt' | 'json' | 'docx' | 'pdf';
};

export type AgentExportConversationResponse = (unknown);

export type AgentListConversationMessagesData = {
    conversationId: string;
    limit?: number;
    skip?: number;
};

export type AgentListConversationMessagesResponse = (Array<MessageOut>);

export type AgentDeleteConversationMessageData = {
    conversationId: string;
    messageId: string;
};

export type AgentDeleteConversationMessageResponse = (unknown);

export type AgentTruncateConversationMessagesData = {
    conversationId: string;
    requestBody: MessageTruncateRequest;
};

export type AgentTruncateConversationMessagesResponse = (unknown);

export type AgentChatData = {
    conversationId: string;
    requestBody: ChatRequest;
};

export type AgentChatResponse = (ChatResponse);

export type AgentCreateMcpServerData = {
    requestBody: MCPServerCreate;
};

export type AgentCreateMcpServerResponse = (MCPServerResponse);

export type AgentListMcpServersData = {
    limit?: number;
    skip?: number;
};

export type AgentListMcpServersResponse = (Array<MCPServerResponse>);

export type AgentGetMcpServerData = {
    serverId: string;
};

export type AgentGetMcpServerResponse = (MCPServerResponse);

export type AgentUpdateMcpServerData = {
    requestBody: MCPServerUpdate;
    serverId: string;
};

export type AgentUpdateMcpServerResponse = (MCPServerResponse);

export type AgentDeleteMcpServerData = {
    serverId: string;
};

export type AgentDeleteMcpServerResponse = (unknown);

export type AgentConnectMcpServerData = {
    serverId: string;
};

export type AgentConnectMcpServerResponse = (MCPServerConnectResponse);

export type AgentListSkillsResponse = (Array<{
    [key: string]: unknown;
}>);

export type AgentGetSkillDetailData = {
    skillName: string;
};

export type AgentGetSkillDetailResponse = ({
    [key: string]: unknown;
});

export type AgentDeleteSkillData = {
    skillName: string;
};

export type AgentDeleteSkillResponse = ({
    [key: string]: unknown;
});

export type AgentScanSkillsResponse = ({
    [key: string]: unknown;
});

export type AgentInstallSkillData = {
    formData: Body_agent_install_skill;
};

export type AgentInstallSkillResponse = ({
    [key: string]: unknown;
});

export type KnowledgeBaseListKbsResponse = (Array<KBOut>);

export type KnowledgeBaseCreateKbData = {
    requestBody: KBCreate;
};

export type KnowledgeBaseCreateKbResponse = (KBOut);

export type KnowledgeBaseListTrashResponse = (Array<TrashDocumentOut>);

export type KnowledgeBaseRestoreTrashedDocumentData = {
    docId: string;
};

export type KnowledgeBaseRestoreTrashedDocumentResponse = (DocumentOut);

export type KnowledgeBasePurgeTrashedDocumentData = {
    docId: string;
};

export type KnowledgeBasePurgeTrashedDocumentResponse = (unknown);

export type KnowledgeBaseGetKbData = {
    kbId: string;
};

export type KnowledgeBaseGetKbResponse = (KBOut);

export type KnowledgeBaseDeleteKbData = {
    kbId: string;
};

export type KnowledgeBaseDeleteKbResponse = (unknown);

export type KnowledgeBaseUploadKbDocumentData = {
    formData: Body_knowledge_base_upload_kb_document;
    kbId: string;
};

export type KnowledgeBaseUploadKbDocumentResponse = (DocumentOut);

export type KnowledgeBaseListKbDocumentsData = {
    kbId: string;
};

export type KnowledgeBaseListKbDocumentsResponse = (Array<DocumentOut>);

export type KnowledgeBaseDeleteKbDocumentData = {
    docId: string;
    kbId: string;
};

export type KnowledgeBaseDeleteKbDocumentResponse = (unknown);

export type KnowledgeBaseQueryKbData = {
    kbId: string;
    requestBody: KBQueryRequest;
};

export type KnowledgeBaseQueryKbResponse = (KBQueryResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProvidersListProvidersResponse = (Array<ProviderOut>);

export type ProvidersCreateProviderData = {
    requestBody: ProviderCreate;
};

export type ProvidersCreateProviderResponse = (ProviderOut);

export type ProvidersUpdateProviderData = {
    providerId: string;
    requestBody: ProviderUpdate;
};

export type ProvidersUpdateProviderResponse = (ProviderOut);

export type ProvidersDeleteProviderData = {
    providerId: string;
};

export type ProvidersDeleteProviderResponse = (unknown);

export type SettingsReadDeploymentSettingsResponse = (DeploymentSettingsPublic);

export type SettingsUpdateDeploymentSettingsData = {
    requestBody: DeploymentSettingsUpdate;
};

export type SettingsUpdateDeploymentSettingsResponse = (DeploymentSettingsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadMySystemPromptResponse = (SystemPromptPublic);

export type UsersUpdateMySystemPromptData = {
    requestBody: SystemPromptUpdate;
};

export type UsersUpdateMySystemPromptResponse = (SystemPromptPublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsReadPublicSettingsResponse = (PublicSettings);