/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSkillsRouteImport } from './routes/_layout/skills'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProvidersRouteImport } from './routes/_layout/providers'
import { Route as LayoutPersonasRouteImport } from './routes/_layout/personas'
import { Route as LayoutMcpRouteImport } from './routes/_layout/mcp'
import { Route as LayoutKnowledgeBaseRouteImport } from './routes/_layout/knowledge-base'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutKnowledgeBaseIndexRouteImport } from './routes/_layout/knowledge-base.index'
import { Route as LayoutKnowledgeBaseTrashRouteImport } from './routes/_layout/knowledge-base.trash'
import { Route as LayoutKnowledgeBaseKbIdRouteImport } from './routes/_layout/knowledge-base.$kbId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillsRoute = LayoutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProvidersRoute = LayoutProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPersonasRoute = LayoutPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMcpRoute = LayoutMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeBaseRoute = LayoutKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeBaseIndexRoute =
  LayoutKnowledgeBaseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutKnowledgeBaseRoute,
  } as any)
const LayoutKnowledgeBaseTrashRoute =
  LayoutKnowledgeBaseTrashRouteImport.update({
    id: '/trash',
    path: '/trash',
    getParentRoute: () => LayoutKnowledgeBaseRoute,
  } as any)
const LayoutKnowledgeBaseKbIdRoute = LayoutKnowledgeBaseKbIdRouteImport.update({
  id: '/$kbId',
  path: '/$kbId',
  getParentRoute: () => LayoutKnowledgeBaseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/chat': typeof LayoutChatRoute
  '/knowledge-base': typeof LayoutKnowledgeBaseRouteWithChildren
  '/mcp': typeof LayoutMcpRoute
  '/personas': typeof LayoutPersonasRoute
  '/providers': typeof LayoutProvidersRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/knowledge-base/$kbId': typeof LayoutKnowledgeBaseKbIdRoute
  '/knowledge-base/trash': typeof LayoutKnowledgeBaseTrashRoute
  '/knowledge-base/': typeof LayoutKnowledgeBaseIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/chat': typeof LayoutChatRoute
  '/mcp': typeof LayoutMcpRoute
  '/personas': typeof LayoutPersonasRoute
  '/providers': typeof LayoutProvidersRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/': typeof LayoutIndexRoute
  '/knowledge-base/$kbId': typeof LayoutKnowledgeBaseKbIdRoute
  '/knowledge-base/trash': typeof LayoutKnowledgeBaseTrashRoute
  '/knowledge-base': typeof LayoutKnowledgeBaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/knowledge-base': typeof LayoutKnowledgeBaseRouteWithChildren
  '/_layout/mcp': typeof LayoutMcpRoute
  '/_layout/personas': typeof LayoutPersonasRoute
  '/_layout/providers': typeof LayoutProvidersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/skills': typeof LayoutSkillsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/knowledge-base/$kbId': typeof LayoutKnowledgeBaseKbIdRoute
  '/_layout/knowledge-base/trash': typeof LayoutKnowledgeBaseTrashRoute
  '/_layout/knowledge-base/': typeof LayoutKnowledgeBaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/knowledge-base'
    | '/mcp'
    | '/personas'
    | '/providers'
    | '/settings'
    | '/skills'
    | '/knowledge-base/$kbId'
    | '/knowledge-base/trash'
    | '/knowledge-base/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/mcp'
    | '/personas'
    | '/providers'
    | '/settings'
    | '/skills'
    | '/'
    | '/knowledge-base/$kbId'
    | '/knowledge-base/trash'
    | '/knowledge-base'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/chat'
    | '/_layout/knowledge-base'
    | '/_layout/mcp'
    | '/_layout/personas'
    | '/_layout/providers'
    | '/_layout/settings'
    | '/_layout/skills'
    | '/_layout/'
    | '/_layout/knowledge-base/$kbId'
    | '/_layout/knowledge-base/trash'
    | '/_layout/knowledge-base/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skills': {
      id: '/_layout/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof LayoutSkillsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/providers': {
      id: '/_layout/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof LayoutProvidersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/personas': {
      id: '/_layout/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof LayoutPersonasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mcp': {
      id: '/_layout/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof LayoutMcpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-base': {
      id: '/_layout/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof LayoutKnowledgeBaseRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-base/': {
      id: '/_layout/knowledge-base/'
      path: '/'
      fullPath: '/knowledge-base/'
      preLoaderRoute: typeof LayoutKnowledgeBaseIndexRouteImport
      parentRoute: typeof LayoutKnowledgeBaseRoute
    }
    '/_layout/knowledge-base/trash': {
      id: '/_layout/knowledge-base/trash'
      path: '/trash'
      fullPath: '/knowledge-base/trash'
      preLoaderRoute: typeof LayoutKnowledgeBaseTrashRouteImport
      parentRoute: typeof LayoutKnowledgeBaseRoute
    }
    '/_layout/knowledge-base/$kbId': {
      id: '/_layout/knowledge-base/$kbId'
      path: '/$kbId'
      fullPath: '/knowledge-base/$kbId'
      preLoaderRoute: typeof LayoutKnowledgeBaseKbIdRouteImport
      parentRoute: typeof LayoutKnowledgeBaseRoute
    }
  }
}

interface LayoutKnowledgeBaseRouteChildren {
  LayoutKnowledgeBaseKbIdRoute: typeof LayoutKnowledgeBaseKbIdRoute
  LayoutKnowledgeBaseTrashRoute: typeof LayoutKnowledgeBaseTrashRoute
  LayoutKnowledgeBaseIndexRoute: typeof LayoutKnowledgeBaseIndexRoute
}

const LayoutKnowledgeBaseRouteChildren: LayoutKnowledgeBaseRouteChildren = {
  LayoutKnowledgeBaseKbIdRoute: LayoutKnowledgeBaseKbIdRoute,
  LayoutKnowledgeBaseTrashRoute: LayoutKnowledgeBaseTrashRoute,
  LayoutKnowledgeBaseIndexRoute: LayoutKnowledgeBaseIndexRoute,
}

const LayoutKnowledgeBaseRouteWithChildren =
  LayoutKnowledgeBaseRoute._addFileChildren(LayoutKnowledgeBaseRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutKnowledgeBaseRoute: typeof LayoutKnowledgeBaseRouteWithChildren
  LayoutMcpRoute: typeof LayoutMcpRoute
  LayoutPersonasRoute: typeof LayoutPersonasRoute
  LayoutProvidersRoute: typeof LayoutProvidersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSkillsRoute: typeof LayoutSkillsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutKnowledgeBaseRoute: LayoutKnowledgeBaseRouteWithChildren,
  LayoutMcpRoute: LayoutMcpRoute,
  LayoutPersonasRoute: LayoutPersonasRoute,
  LayoutProvidersRoute: LayoutProvidersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSkillsRoute: LayoutSkillsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
