"""CRUD operations module."""

# ⚠️ create_item 已随 D1.4 删除（模板残留的示例待办表 item）
from app.core.crud.user_item import (  # noqa: F401
    create_user,
    update_user,
    get_user_by_email,
    authenticate,
)
from app.core.crud.agent import (  # noqa: F401
    create_provider_config,
    get_provider_config,
    list_provider_configs,
    update_provider_config,
    delete_provider_config,
    create_conversation,
    get_conversation,
    list_conversations,
    delete_conversation,
    add_message,
    get_messages,
    create_knowledge_base,
    get_knowledge_base,
    list_knowledge_bases,
    delete_knowledge_base,
    create_document,
    get_document,
    list_documents,
    create_mcp_server,
    get_mcp_server,
    list_mcp_servers,
    update_mcp_server,
    delete_mcp_server,
    get_skill,
    list_skills,
    create_skill,
    delete_skill,
    create_persona,
    get_persona,
    list_personas,
    delete_persona,
    create_agent_run,
    get_agent_run,
    list_agent_runs,
    agent_run_stats,
    update_agent_run,
)
