"""scripts/wheelhouse.py 的纯函数测试。

刻意**不依赖网络、也不要求 wheelhouse/ 目录存在**（该目录被 gitignore，新克隆的仓库里没有）
—— 否则这个测试会在干净环境里挂掉，而它本来就是为了防「干净环境里静默缺件」。
"""

from __future__ import annotations

import pytest

from scripts.wheelhouse import (
    EXCLUDED_PACKAGES,
    REQUIREMENTS_FILE,
    RequirementBlock,
    build_download_command,
    check_wheelhouse,
    missing_blocks,
    normalize_name,
    parse_artifact_filename,
    parse_blocks,
    parse_requirement_line,
    render_download_requirements,
    render_requirements,
    strip_banner,
    strip_excluded_packages,
)

SAMPLE_EXPORT = """\
# This file was autogenerated by uv via the following command:
#    uv export --frozen --all-extras --no-dev --package app --format requirements.txt -o tmp.txt --no-emit-package app
aiohappyeyeballs==2.6.2 \\
    --hash=sha256:aaaa \\
    --hash=sha256:bbbb
    # via aiohttp
colorama==0.4.6 ; sys_platform == 'win32' \\
    --hash=sha256:cccc \\
    --hash=sha256:dddd
    #   click
    #   tqdm
faiss-cpu==1.15.0 ; sys_platform != 'win32' \\
    --hash=sha256:eeee
    # via pymilvus
"""


def test_normalize_name_follows_pep503() -> None:
    assert normalize_name("faiss_cpu") == "faiss-cpu"
    assert normalize_name("zope.interface") == "zope-interface"
    assert normalize_name("Python-Docx") == "python-docx"


@pytest.mark.parametrize(
    ("line", "expected"),
    [
        ("aiohappyeyeballs==2.6.2 \\\n", ("aiohappyeyeballs", "2.6.2", "")),
        (
            "faiss-cpu==1.15.0 ; sys_platform != 'win32' \\\n",
            ("faiss-cpu", "1.15.0", "sys_platform != 'win32'"),
        ),
        ("jieba==0.42.1\n", ("jieba", "0.42.1", "")),
        ("python_docx==1.2.0\n", ("python-docx", "1.2.0", "")),
    ],
)
def test_parse_requirement_line(line: str, expected: tuple[str, str, str]) -> None:
    assert parse_requirement_line(line) == expected


@pytest.mark.parametrize(
    "line",
    [
        "",
        "\n",
        "    # via aiohttp\n",
        "    #   click\n",
        "    --hash=sha256:aaaa\n",
        "--index-url x\n",
    ],
)
def test_parse_requirement_line_ignores_non_declarations(line: str) -> None:
    assert parse_requirement_line(line) is None


def test_parse_blocks_collects_hashes_and_markers() -> None:
    blocks = parse_blocks(SAMPLE_EXPORT)
    assert [b.name for b in blocks] == ["aiohappyeyeballs", "colorama", "faiss-cpu"]
    assert blocks[0] == RequirementBlock(
        name="aiohappyeyeballs",
        version="2.6.2",
        marker="",
        hashes=("sha256:aaaa", "sha256:bbbb"),
    )
    assert blocks[1].marker == "sys_platform == 'win32'"
    assert blocks[2] == RequirementBlock(
        name="faiss-cpu",
        version="1.15.0",
        marker="sys_platform != 'win32'",
        hashes=("sha256:eeee",),
    )


def test_strip_banner_drops_only_leading_comments() -> None:
    stripped = strip_banner(SAMPLE_EXPORT)
    assert stripped.startswith("aiohappyeyeballs==2.6.2")
    # 块内的 # via 注释必须保留（它不是横幅）
    assert "# via aiohttp" in stripped


def test_strip_excluded_packages_removes_whole_block() -> None:
    result = strip_excluded_packages(SAMPLE_EXPORT)
    assert "colorama" not in result
    assert "#   click" not in result  # 续行/注释行一起删
    # 其余内容逐字节保留
    assert "aiohappyeyeballs==2.6.2" in result
    assert "    --hash=sha256:bbbb\n" in result
    assert "faiss-cpu==1.15.0 ; sys_platform != 'win32'" in result


def test_strip_excluded_packages_removes_single_line_block() -> None:
    text = "tzdata==2025.2\nkept==1.0\n"
    assert strip_excluded_packages(text) == "kept==1.0\n"


def test_render_requirements_normalizes_banner_and_filters() -> None:
    rendered = render_requirements(SAMPLE_EXPORT)
    lines = rendered.splitlines()
    assert lines[0] == "# This file was autogenerated by uv via the following command:"
    assert lines[1].endswith("-o wheelhouse-req.txt")
    assert "--no-emit-package app" in lines[1]
    names = {
        parse_requirement_line(line)[0]
        for line in lines
        if parse_requirement_line(line)
    }
    assert names & EXCLUDED_PACKAGES == set()
    assert names == {"aiohappyeyeballs", "faiss-cpu"}


def test_render_requirements_is_stable_for_different_output_names() -> None:
    # 横幅里的 -o 路径不同不该导致内容差异（check 靠这一点忽略横幅）
    assert strip_banner(render_requirements(SAMPLE_EXPORT)) == strip_banner(
        render_requirements(SAMPLE_EXPORT, output_name="whatever.txt")
    )


def test_render_download_requirements_strips_markers() -> None:
    blocks = parse_blocks(SAMPLE_EXPORT)
    rendered = render_download_requirements([blocks[1], blocks[2]])
    assert ";" not in rendered  # 标记必须去掉，否则 pip 按本机平台跳过 linux-only 包
    assert rendered.splitlines()[0] == "colorama==0.4.6 \\"
    assert rendered.splitlines()[1] == "    --hash=sha256:cccc \\"
    assert rendered.splitlines()[2] == "    --hash=sha256:dddd"  # 最后一行不带续行符


def test_render_download_requirements_without_hashes() -> None:
    block = RequirementBlock(name="jieba", version="0.42.1", marker="", hashes=())
    assert render_download_requirements([block]) == "jieba==0.42.1\n"


def test_build_download_command_for_binaries() -> None:
    command = build_download_command(REQUIREMENTS_FILE, binaries=True)
    assert command[:2] == ["uv", "run"]  # 禁止裸 python/pip
    assert command[-1] == "--only-binary=:all:"
    assert "--python-version" in command
    assert command[command.index("--python-version") + 1] == "3.13"
    assert command.count("--platform") >= 1


def test_build_download_command_for_sdist_only_packages() -> None:
    command = build_download_command(REQUIREMENTS_FILE, binaries=False)
    # jieba 在 PyPI 只有 sdist：--only-binary=:all: 会直接报找不到发行版
    assert "--only-binary=:all:" not in command
    assert "--no-binary=:all:" in command
    assert "--platform" not in command


@pytest.mark.parametrize(
    ("filename", "expected"),
    [
        (
            "faiss_cpu-1.15.0-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
            ("faiss-cpu", "1.15.0"),
        ),
        ("jieba-0.42.1.tar.gz", ("jieba", "0.42.1")),
        ("python_docx-1.2.0-py3-none-any.whl", ("python-docx", "1.2.0")),
        ("ranklib-2.0.zip", ("ranklib", "2.0")),
    ],
)
def test_parse_artifact_filename(filename: str, expected: tuple[str, str]) -> None:
    assert parse_artifact_filename(filename) == expected


@pytest.mark.parametrize(
    "filename", ["README.md", "no-version.whl", "wheelhouse-req.txt"]
)
def test_parse_artifact_filename_rejects_unknown(filename: str) -> None:
    assert parse_artifact_filename(filename) is None


def test_check_wheelhouse_passes_when_everything_matches() -> None:
    blocks = [
        RequirementBlock(
            name="jieba", version="0.42.1", marker="", hashes=("sha256:aaaa",)
        )
    ]
    assert check_wheelhouse(blocks, {"jieba-0.42.1.tar.gz": "aaaa"}) == []


def test_check_wheelhouse_reports_missing_file() -> None:
    blocks = [
        RequirementBlock(
            name="jieba", version="0.42.1", marker="", hashes=("sha256:aaaa",)
        )
    ]
    problems = check_wheelhouse(blocks, {})
    assert problems == ["jieba==0.42.1：wheelhouse 里缺少对应文件"]


def test_check_wheelhouse_reports_hash_mismatch() -> None:
    blocks = [
        RequirementBlock(
            name="jieba", version="0.42.1", marker="", hashes=("sha256:aaaa",)
        )
    ]
    problems = check_wheelhouse(blocks, {"jieba-0.42.1.tar.gz": "zzzz"})
    assert len(problems) == 1
    assert "哈希与清单不符" in problems[0]


def test_check_wheelhouse_reports_stale_file() -> None:
    blocks = [
        RequirementBlock(
            name="jieba", version="0.42.1", marker="", hashes=("sha256:aaaa",)
        )
    ]
    artifacts = {"jieba-0.42.1.tar.gz": "aaaa", "jieba-0.41.0.tar.gz": "bbbb"}
    problems = check_wheelhouse(blocks, artifacts)
    assert problems == ["jieba-0.41.0.tar.gz：清单里没有对应条目（旧版本残留，应删除）"]


def test_check_wheelhouse_reports_unparsable_filename() -> None:
    assert check_wheelhouse([], {"README.md": "abcd"}) == [
        "README.md：文件名解析不出包名/版本，无法校验"
    ]


def test_missing_blocks_lists_only_absent_packages() -> None:
    blocks = parse_blocks(SAMPLE_EXPORT)
    missing = missing_blocks(
        blocks, {"aiohappyeyeballs-2.6.2-py3-none-any.whl": "aaaa"}
    )
    assert [b.name for b in missing] == ["colorama", "faiss-cpu"]


def test_committed_requirements_excludes_win32_packages() -> None:
    """仓库里提交的清单必须是**过滤后**的（防止有人直接跑裸 uv export 覆盖它）。"""
    content = REQUIREMENTS_FILE.read_text(encoding="utf-8")
    names = {
        line.split("==", 1)[0]
        for line in content.splitlines()
        if parse_requirement_line(line)
    }
    assert names, "清单解析为空，格式可能已变"
    assert names & EXCLUDED_PACKAGES == set()
